language: node_js

node_js:
  - 9

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install

script:
  - yarn build
  - yarn test

deploy:
  provider: heroku
  app: rchesnokov-loftschool-react-js
  api_key:
    secure: $HEROKU_KEY

