// flow-typed signature: c13f8e9ef3c23baf24bb77cbdfb9e928
// flow-typed version: <<STUB>>/react-particles-js_v^2.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-particles-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-particles-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-particles-js/lib/particles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-particles-js/lib/particles.js' {
  declare module.exports: $Exports<'react-particles-js/lib/particles'>;
}
